apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-gateway.fullname" . }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.env.PORT | quote }}
  {{- if .Values.env.CORS_ORIGIN }}
  CORS_ORIGIN: {{ .Values.env.CORS_ORIGIN | quote }}
  {{- end }}
