{{- if and .Values.ingress.enabled (eq (.Values.ingress.className | default "") "traefik") -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "yapp.fullname" . }}-strip-api-prefix
  labels:
    {{- include "yapp.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - /api
{{- end }}
